#!/bin/bash

# Quick Start - AutoPrime Deploy

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         🚗 AutoPrime - Deploy Rápido para Nuvem          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Este projeto está 100% pronto para deploy em produção!"
echo ""
echo "📋 CREDENCIAIS DO BANCO DE DADOS:"
echo "   Host: localhost (ou seu host MySQL)"
echo "   Porta: 3306"
echo "   Database: carros"
echo "   User: root"
echo "   Password: root"
echo ""
echo "🎯 O QUE ACONTECE AUTOMATICAMENTE:"
echo "   ✓ Conexão com MySQL"
echo "   ✓ Criação do banco 'carros' se não existir"
echo "   ✓ Criação da tabela 'carros' se não existir"
echo "   ✓ Inserção de dados de exemplo (se vazio)"
echo "   ✓ Inicialização com Gunicorn na porta 8080"
echo ""
echo "🚀 PARA INICIAR O SERVIDOR:"
echo ""
echo "   1. Certifique-se que MySQL está rodando:"
echo "      sudo service mysql start"
echo ""
echo "   2. Execute o script de setup:"
echo "      ./setup_and_run.sh"
echo ""
echo "   Ou simplesmente:"
echo "      python app.py"
echo ""
echo "🌐 ENDPOINTS DISPONÍVEIS:"
echo "   • http://localhost:8080/ - Interface Web"
echo "   • http://localhost:8080/health - Health Check"
echo "   • http://localhost:8080/api/listarCarros - API REST"
echo ""
echo "☁️  DEPLOY EM NUVEM:"
echo ""
echo "   1. Suba os arquivos para seu servidor"
echo "   2. Configure MySQL (ou use MySQL gerenciado)"
echo "   3. Ajuste variáveis de ambiente em .env:"
echo "      DB_HOST=seu-host-mysql"
echo "      DB_USER=root"
echo "      DB_PASSWORD=root"
echo "   4. Execute: ./setup_and_run.sh"
echo ""
echo "📚 DOCUMENTAÇÃO COMPLETA:"
echo "   • PRONTO_PARA_DEPLOY.md - Visão geral"
echo "   • DEPLOY_CLOUD.md - Deploy em AWS, Azure, GCP, etc."
echo "   • README_DEPLOY.md - Instruções detalhadas"
echo ""
echo "🐳 DOCKER:"
echo "   docker-compose up -d"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ Projeto pronto! Basta configurar o MySQL e executar! ✨"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
